[project]
name = 'stacks-svg'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.clarity-bitcoin-lib-v1"

[contracts.svg]
path = 'contracts/svg.clar'
clarity_version = 1

[contracts.parts]
path = 'contracts/parts.clar'
clarity_version = 1

[repl.analysis]
passes = ['check_checker']

[contracts.commission-trait]
path = "contracts/commission-trait.clar"

[contracts.nft-trait]
path = "contracts/nft-trait.clar"

[contracts.stacks-svg-nft]
path = "contracts/stacks-svg-nft.clar"
depends_on = ["nft-trait", "commission-trait"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
