[project]
name = 'stacks-svg'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.parts]
path = 'contracts/parts.clar'
clarity_version = 1

[contracts.svg]
path = 'contracts/svg.clar'
clarity_version = 1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
